# Generated by Django 5.2.1 on 2025-05-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentViewSet',
        ),
    ]
